- src/game/Object/Unit.cpp
- src/game/Object/Unit.h
This can be used to tell if a creature has reached or is near to a
stated waypoint (coordinates)
> New function added - IsNearWaypoint

- src/modules/SD2/scripts/kalimdor/felwood.cpp
- src/modules/SD2/scripts/kalimdor/temple_of_ahnqiraj/boss_skeram.cpp
AQ40 Skeram Image FIX by Arkadus
> AQ40 Skeram Image FIX

- src/modules/SD2/scripts/kalimdor/razorfen_downs/razorfen_downs.cpp
This script will make the gong in RFD spawn the waves of creatures,
culminating in the spawning of Tuten'kash (boss)
> Tuken'kash gong (RFD) scripted

- src/modules/SD2/scripts/eastern_kingdoms/karazhan/boss_netherspite.cpp
baummangos fix - Karazhan portal implementation for boss netherspite
> baummangos fix - Karazhan portal implementation for boss netherspite

- src/modules/SD2/scripts/eastern_kingdoms/stratholme/instance_stratholme.cpp
- src/modules/SD2/scripts/eastern_kingdoms/stratholme/stratholme.h
The Unforgiven (stratholme) - identifier initialisation of
m_bTheUnforgivenSpawnHasTriggered moved to instance_stratholme.cpp
> Strat - The Unforgiven script code correction

- src/shared/revision_sql.h
Revision change for World DB update
> Revision change for World DB update

- src/game/Object/Creature.cpp
- src/game/Object/Unit.cpp
Fix by Arkadus - Polymorph fix
> Fix by Arkadus - Polymorph fix

- src/game/Object/CreatureEventAI.cpp
- src/game/Object/CreatureEventAI.h
- src/game/Object/CreatureEventAIMgr.cpp
EventAT Action Types synched with Zero and One
Actions 47 to 50 synched up
ACTION_T_SET_STAND_STATE
ACTION_T_CHANGE_MOVEMENT
ACTION_T_SUMMON_UNIQUE
ACTION_T_EMOTE_TARGET
> EventAT Action Types synched with Zero and One

- src/shared/revision_sql.h
> World DB Revision change

- src/game/Object/ObjectMgr.cpp
- src/game/Object/ObjectMgr.h
Based on the gameobject Entry and range passed to it, this looks for the
nearest gameobject to the source within that proximity.
> New condition added (re condition table)

- src/shared/revision_sql.h
> Revision change (World)

- src/modules/SD2/scripts/world/item_scripts.cpp
This makes the potion only usable in Blades Edge
> SylvainNeau (author) - Ogre Brew script

- src/shared/revision_sql.h
> Revision update (World)

- src/shared/revision_sql.h
> Revision updated (World)

- src/modules/SD2/scripts/world/item_scripts.cpp
> Ogre Brew scripts replaced

- src/shared/revision_sql.h
> Revision updated (World DB)

- .travis.yml
- src/framework/Platform/Define.h
- src/tools/Movemap-Generator/TerrainBuilder.cpp
Also:
- Fix a condition in MMap generator tool (requires rebuilding of mmaps).
- Make Travis happy.
> Fix build error due to 226f27f.

- src/framework/Utilities/UnorderedMapSet.h
- src/game/Object/ObjectMgr.cpp
- src/game/WorldHandlers/CalendarHandler.cpp
- src/mangosd/CMakeLists.txt
- src/mangosd/Comm/CliRunnable.cpp
- src/mangosd/WorldRunnable.cpp
- src/modules/SD2/scripts/northrend/naxxramas/naxxramas.h
- src/tools/vmap-extractor/CMakeLists.txt
- src/tools/vmap-extractor/adtfile.cpp
- src/tools/vmap-extractor/adtfile.h
- src/tools/vmap-extractor/dbcfile.cpp
- src/tools/vmap-extractor/model.cpp
- src/tools/vmap-extractor/model.h
- src/tools/vmap-extractor/modelheaders.h
- src/tools/vmap-extractor/vec3d.h
- src/tools/vmap-extractor/vmapexport.cpp
- src/tools/vmap-extractor/vmapexport.h
- src/tools/vmap-extractor/wdtfile.cpp
- src/tools/vmap-extractor/wdtfile.h
- src/tools/vmap-extractor/wmo.cpp
- src/tools/vmap-extractor/wmo.h
Includes:
- fix world server freeze on shutdown (ported from ZERO)
- new vmap-extractor
- fix out-of-bounds warnings in SD2
- minor corrections in code
> More fixes

- src/game/Object/Unit.cpp
- src/game/WorldHandlers/Spell.h
Accessor functions created for protected member, m_selfContainer
> Spell class - Fix for inaccessible class data

- src/game/Object/Player.cpp
- src/game/Object/Player.h
- src/game/Server/Opcodes.h
commit 2622b33 on cabfever's repo
> (author Olion17) Chest with quest loot deactivation (2622b33)

- src/game/Server/DBCStores.cpp
- src/game/Server/DBCStores.h
Case-insensitive channel name comparison for "world".
commit 43860fb on cabfever's repo
> (Author: Olion17) Server-owned world channel

- src/game/Object/Pet.cpp
- src/game/Object/Pet.h
- src/game/Object/Unit.h
(from cab's repo) added UpdateSpeed function to Pet
Author: probably Olion, but not certain.
> (from cab's repo) added UpdateSpeed function

- src/game/Object/Unit.cpp
- src/game/WorldHandlers/MovementHandler.cpp
- src/shared/Utilities/WorldPacket.h
Changed type from Opcode to uint16.
Stopped using the Opcode type in the previous commit.
> Type conversion mismatch correction

- src/game/AuctionHouseBot/AuctionHouseBot.cpp
- src/game/AuctionHouseBot/AuctionHouseBot.h
- src/game/AuctionHouseBot/ahbot.conf.dist.in
- src/game/Object/AuctionHouseMgr.cpp
- src/game/Object/AuctionHouseMgr.h
Auction House Seller Option, ported from Zero
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/server/131)
> Auction House Seller Option, ported from Zero

- src/game/WorldHandlers/SpellEffects.cpp
cmangos BRD Grimm Guzzler updates
Update to the latest version of ScriptDev3
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/server/137)
> BRD Grimm Guzzler related updates

- cmake/SetDefinitions.cmake
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/server/138)
> Revert [0935b66]. Breaks Eluna.

- src/game/WorldHandlers/World.cpp
This may require you to change CreateLuaEvent timers to half of what they were.
Merge when checks succeed :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/server/141)
> Eluna update version - Fix duplicate timer update

- src/game/Object/Pet.cpp
Port from Zero
https://github.com/MangosZero/Server/commit/a0a25be
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/server/143)
> Hunter Pet speed

- src/game/Object/Unit.cpp
Another rogue stealth tweak.
-- Credit to Magic
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/server/147)
> Another rogue stealth tweak.

- src/game/WorldHandlers/SpellAuras.cpp
The well fed buff will now apply when eating the following,
- Bobbing Apple
- Winter Veil Cookie
- Buttermilk Delight
- Dark Desire
- Very Berry Cream
- Sweet Surprise
- Noblegarden Chocolate
- Bread of the Dead
Thanks to @H0zen for providing the code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/server/157)
> well fed buff

- src/game/WorldHandlers/SpellAuras.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/server/158)
> Cosmetic fixes of previous commit

- src/game/WorldHandlers/Spell.cpp
Copy from M1 update
Thanks, @H0zen
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/server/159)
> Minor  pet/Spell update

- src/game/WorldHandlers/ChatHandler.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/server/160)
> Fix whisper blocking

- src/game/MotionGenerators/MotionMaster.h
- src/game/Warden/Warden.cpp
- src/game/WorldHandlers/InstanceData.h
- src/game/WorldHandlers/MoveMap.h
- src/game/WorldHandlers/ScriptMgr.cpp
- src/game/WorldHandlers/Weather.cpp
- src/game/WorldHandlers/World.cpp
Fixes errors when compiling without PCH.
Also updates Eluna to the latest version, which is required to fix some of the errors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/server/163)
> Fix non PCH build and update Eluna

- src/game/Object/Player.cpp
- src/game/WorldHandlers/World.cpp
Lich king added another profession bringing the total to 11 (https://wow.gamepedia.com/Profession#Primary_professions).
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/server/167)
> Increase profession limit

- src/game/Object/ObjectMgr.cpp
- src/game/Object/Player.cpp
- src/game/WorldHandlers/CalendarHandler.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/server/168)
> Missing delimiter

- linux/getmangos.sh
Updated libmysqlclient source.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/server/169)
> Updating Debian Sources

- linux/getmangos.sh
`$GAMEPATH` was not wrapped like this `"$GAMEPATH"`
`/path/to/World\ of\ Warcraft\` works now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/server/172)
> Fixes Error "There is no game at this location"

- src/game/Server/Opcodes.cpp
- src/game/Server/WorldSession.h
- src/game/WorldHandlers/MiscHandler.cpp
The command forcefully removes the player from the server. Like kick, but on self.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/server/177)
> Implemented the 'bootme' client command handler

- src/tools/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/server/179)
> Fixed duplicated extractor files and missing dir

- src/game/Object/Object.h
- src/game/Server/Opcodes.cpp
- src/game/Server/WorldSession.h
- src/game/WorldHandlers/MiscHandler.cpp
Usage: cgo <objectID>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/server/178)
> Implemented the 'creategameobject' client command handler

- src/game/Server/Opcodes.cpp
- src/game/Server/WorldSession.h
- src/game/WorldHandlers/MiscHandler.cpp
Usage: money < copper>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/server/182)
> Implemented the SetMoney cheat command handler

- CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/server/183)
> CMakelist in sync with release point

- src/game/Object/Unit.cpp
* https://www.getmangos.eu/bug-tracker/mangos-one/glancing-blow-chance-r1723/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/server/184)
> Changing the Glancing Blow chance to 25%
