- src/game/WorldHandlers/LFGHandler.cpp
- src/game/WorldHandlers/LFGMgr.cpp
Although nullptr worked under MS Windows, it threw up an "unresolved
external symbol error" under Linux.
Replaced nullptr with NULL in 2 files.
> Build error using nullptr under Linux

- src/modules/SD2/scripts/world/npcs_special.cpp
Creature was set to not attackable.
Faction ID changed to Demon (73)
> Guardian of Blizzard no combat fix

- src/shared/revision_sql.h
The original length of the name was not to the server's liking
> World DB revision change/correction

- src/modules/SD2/scripts/kalimdor/tanaris.cpp
Had to do this again, due to the commits going out of synch... oops
Visibilty whne not in GM mode fixed.
Total time spent in world reduced to 3 minutes, due to the setting of
respawn time seeming not to work.
- Sailor boys were respawning after dying.
Pirates now spawn further away, making it look a  lot better.
Pirates now run towards the player's toon, ready for action, oooerr ;)
> Totally Cueergo Gold's Script updated

- src/game/Object/AuctionHouseMgr.cpp
- src/game/Object/Item.cpp
- src/game/Object/Item.h
- When creating items with charges (ie Amulet of the Moon), the server wrongly inform the client about the charges they have.
- This fixes issue [203](https://www.getmangos.eu/issue.php?issueid=203)
> [Core] Fix charged items auctioneering.

- src/game/Object/Unit.cpp
@billy1arm 
- It's amazing how this typo went unnoticed. The whole proc system was broken.
- guilty commit https://github.com/mangostwo/server/commit/216fdeaed57efa26b7638b3c068180426cefac59#diff-b1318d9ecce2e0c12047a2d2c24da46c
> Fix proc system.

- src/game/Object/Unit.cpp
The new version resulted in Travis throwing and error: parameter may not
have variably modified type.
> Reverting back to the previous version of the code.

- src/game/WorldHandlers/UnitAuraProcHandler.cpp
The Aura for the enchant Blood Draining, did not heal when active. This fix
corrected that problem.
Issue and fix found here in the tracker.
https://www.getmangos.eu/bug-tracker/mangos-two/Blood-Draining-not-work-on-hea-r17/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/server/139)
> Fix Blood Draining enchant aura

- src/game/WorldHandlers/SpellEffects.cpp
Cmangos Correction.
[12896] Use pet level modifiers for SPELL_EFFECT_SUMMON_PET (56)
Close #155
Signed-off-by: Xfurry <xfurry@scriptdev2.com>
https://github.com/cmangos/mangos-wotlk/commit/622dc60
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/server/140)
> Use pet level modifiers for SPELL_EFFECT_SUMMON_PET (56)

- src/game/Object/Player.cpp
- src/game/Object/Unit.cpp
- src/game/WorldHandlers/AchievementMgr.cpp
- src/game/WorldHandlers/SpellAuras.cpp
Instead of calculation the total number of items in player's
inventory/bank/equipment
use counter for count every new stored item.
- Credit found here >> https://github.com/mangosR2/mangos/commit/2fca92e
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/server/142)
> Fix ACHIEVEMENT_CRITERIA_TYPE_OWN_ITEM

- src/game/WorldHandlers/SpellEffects.cpp
- spell 21078 will no longer crash the server when called upon.
- The Eye of Archerus crash in the Death knight starting area has been
crushed and will work as intended.
-- A vere special call out to H0zen for his help once again.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/server/144)
> Game object summon spells

- src/game/Object/Creature.cpp
- src/game/Object/Creature.h
- src/game/Object/CreatureAI.cpp
Add spell school prohibition to interrupts
Creatures now honor spell cooldowns for both behavior and event AI
Fix setting both shadow and arcane resistance from arcane resistance template value
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/server/148)
> Add spell school prohibition to interrupts

- src/game/Object/GameObject.cpp
Fixed with code as it is on vanilla and tbc.
sin must be put in z and cos in w, otherwise object rotate on an horiozntal line in the space (not in a vertical by the player xy coords)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/server/151)
> Fix .gobject add #guid

- src/game/WorldHandlers/Spell.cpp
This will correct the players ability to use Item spell on non aura NPCs
WIP portion of 
https://github.com/cmangos/mangos-wotlk/commit/0d764b4
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/server/153)
> Lazy Peon SpellId Information

- src/game/WorldHandlers/MovementHandler.cpp
Source: https://github.com/cmangos/mangos-wotlk/commit/6224b3e
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/server/154)
> Fix stock unit frames displaying group members as offline after teleport

- src/game/Object/Player.cpp
Check for stances when re-applying passive outdoor-only spells.
Credit: https://github.com/cmangos/mangos-tbc/commit/2ff7cc4
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/server/156)
> Fix Feral Swiftness talent

- src/game/WorldHandlers/Spell.cpp
See bug report: https://www.getmangos.eu/bug-tracker/mangos-two/rough-stone-statue-server-crash-r1627/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/server/165)
> Fixed a bug where destroying a channeling object would crash the server.

- src/game/WorldHandlers/LFGMgr.cpp
Initially reported by JetFox#2538 on Discord.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/server/173)
> Fixed a bug where the Dungeon Finder would cause a crash on queuing

- src/game/ChatCommands/PlayerCommands.cpp
- src/game/Object/Player.cpp
- src/game/Object/Player.h
- src/game/Server/Opcodes.cpp
- src/game/Server/WorldSession.h
- src/game/WorldHandlers/MiscHandler.cpp
This command takes for input a player level and can only be executed on the callee. This prevents accidentally setting the level of an unintended player, as is currently possible with the existing command system.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/server/176)
> Implemented the 'level' cheat command handler

- linux/getmangos.sh
Currently you will encounter this error
```
CMake Error at /usr/share/cmake3/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
Could NOT find BZip2 (missing: BZIP2_LIBRARIES BZIP2_INCLUDE_DIR)
```
After yum install the package bzip2-devel, everything is fine.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/server/187)
> Fix missing bzip2 dependency for CentOS

- src/game/WorldHandlers/ScriptMgr.cpp
Fix double inclusion of DBCStores.cpp by changing include in ScriptMgr.cpp from source to header.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/server/193)
> Fix Linux build

- src/game/Object/Object.cpp
Timed events tied to players are removed when a player teleports from one map to another.
In this PR we change it so that timed evens are no longer removed.
See
* https://github.com/ElunaLuaEngine/ElunaTrinityWotlk/commit/a0d10f8ff0e68cf59cd7b2fd62e985adaeb35d9d
* https://discord.com/channels/817077195817353226/1074254244561031248/1074254244561031248
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/server/194)
> Fix player timed events not carrying over between maps

- src/game/BattleGround/BattleGround.cpp
- src/game/BattleGround/BattleGround.h
- src/game/BattleGround/BattleGroundWS.cpp
This PR provides the server with the functionality to offer XP as a reward in battlegrounds and provides the framework for other battlegrounds to be included.
This PR focuses on Warsong Gulch only. Three ways to earn XP:
1) Flag Capture (Pictured below as 1, 2, 3)
2) Remaining Flags at the end of the match. (Pictured below as 4, 5, 6 -- in this example, it was a 3-0 win for Horde, so 3 remaining flags.)
3) Win (Pictured below as 7)
Values for XP are an approximation and NOT Blizzlike. Using era appropriate videos, we extracted XP gains at different levels. The formula utilized in this PR does not match the values exactly, but does scale very closely.
Thank you to REGNURZA on Discord for identifying the lack of XP provided during battlegrounds and researching videos for XP gains!
Thank you …
> Adding XP Gains to Battlegrounds (Warsong Gulch)

- .github/workflows/core_windows_build.yml
Ensure choco always installs the latest version of OpenSSL, as previous versions may not always be available for download.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/server/198)
> Fix OpenSSL in windows workflow

- src/game/WorldHandlers/LFGMgr.cpp
This  fix will remove a few crash points associated with the Dungeon Finder feature.
It does NOT make everything else work - there are still some issues with fringe cases.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangostwo/server/199)
> Fix crash points associated with LFG.
